substitutions:
  name: "centurion-d5-evo"
  friendly_name: "Centurion D5 Evo"
  comment: "Control your Centurion D5 Evo gate motor remotely."

  relay_1_pin: GPIO21
  relay_2_pin: GPIO19
  relay_3_pin: GPIO18
  relay_4_pin: GPIO05
  led_pin: GPIO22

packages:
  remote_package:
    url: https://github.com/dan-s-github/centurion-d5-evo
    ref: main
    files: 
      - packages/diagnostics.yml
      - packages/gate_control.yml
      - packages/led_evaluator.yml

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${comment}
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name}-fallback"
    password: !secret fallback_hotspot_password

captive_portal:
